### ISSUE TITLE
Doesn't work on Vanilla OS

### ISSUE THREAD

**Issue by ghost** [stuartlangridge/utm_no#3]
The app simply isn't working on [Vanilla OS](https://vanillaos.org/) which is Ubuntu based. The app runs fine in the background, although it doesn't clean URLs.

**Comment by stuartlangridge** [comment]
Hm. That's interesting. It's supposed to work, obviously, so apologies for that. A couple of questions:

* how did you install utm_no? (Snap? Flatpak? From source?)
* are you OK with helping to debug the problem, possibly by running Terminal commands? (It's fine to say no here.)

**Comment by ghost** [comment]
> Hm. That's interesting. It's supposed to work, obviously, so apologies for that. A couple of questions:
> 
>     * how did you install utm_no? (Snap? Flatpak? From source?)
> 
>     * are you OK with helping to debug the problem, possibly by running Terminal commands? (It's fine to say no here.)

Installed via Flatpak, No need to apologize Linux evolves fast apps are bound to break just like any OS. If this was windows, my computer would have probably blue screened ahah

![image](https://user-images.githubusercontent.com/122128828/222271144-8f8f2466-777d-4d35-9f76-1ec07b88acfb.png)

~~~
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/utm_no/__main__.py", line 282, in <module>
    UTMNOIndicator().run()
  File "/app/utm_no/__main__.py", line 278, in run
    Gtk.main()
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 1689, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/lib/python3.9/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
~~~
